### ISSUE TITLE
Isolate only? CARE on metagenomic dataset

### ISSUE THREAD

**Issue by mihkelvaher** [fkallen/CARE#2]
Hi!

While passing in the arguments, coverage `-c` was asked. Does this mean that CARE assumes that the sample is an isolate?

What kind of problems would be expected if CARE was run on a metagenomic dataset and, thus assuming low coverage, setting `-c 1`?

**Comment by fkallen** [comment]
CARE assumes that all reads originate from the same species.  It was never evaluated on a metagenomic dataset. 

I do not know the implications of using a low coverage setting with metagenomic data. The coverage parameter is used to estimate the expected number similar reads, and how they are used for correction.

The main problem with metagenomic data will be that reads of different species will be classified as similar and thus mixed in the correction process.

**Comment by mihkelvaher** [comment]
Classifying corrected (`-c 1`) and uncorrected datasets with kraken gave almost the same results - out of hundreds of hits, only 2 with very low coverage were removed.
I guess this is to be expected as the signal is all over the place.
