### ISSUE TITLE
error during installation - compilation terminated

### ISSUE THREAD

**Issue by desmodus1984** [fkallen/CARE#3]
Hi,
I am interested in corrected my 100 Pe-reads but installation failed.

In the server that I am using CUDA is already pre-installed but I have no idea the directory. I installed thrust in the same directory as CARE, I used that directory, which showed no problem, so during the configure I had the following problems:
./configure --with-thrust-incdir=/fs/scratch/PHS0338/appz/CARE/thrust/
Warning! 
          Could not find CUDA compiler /usr/local/cuda/bin/nvcc. 
          care-gpu cannot be compiled without nvcc.
          Please check that the CUDA directory is correct if you intend to use the GPU version.
          
Warning! 
          Could not find file /usr/local/cuda/include/cub/cub.cuh. 
          care-gpu cannot be compiled without cub.
          Please check that the CUB include directory is correct if you intend to use the GPU version.
          
Prefix: /usr/local
CUDA: /usr/local/cuda
CUB: /usr/local/cuda/include
THRUST: /fs/scratch/PHS0338/appz/CARE/thrust/

But during make, it failed:
make cpu
Compiling src/correct_cpu.cpp to buildcpu/correct_cpu.o
In file included from include/correctionresultprocessing.hpp:5,
                 from src/correct_cpu.cpp:4:
include/hpc_helpers.cuh:6:10: fatal error: hpc_helpers/include/cuda_helpers.cuh: No such file or directory
 #include "hpc_helpers/include/cuda_helpers.cuh"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [buildcpu/correct_cpu.o] Error 1

What can I do to overcome this error?

Thanks;

**Comment by fkallen** [comment]
Hi,
the compilation error suggests that the submodule is not initialized properly. Did you clone the project using `git clone --recurse-submodules url` ? 
If not, please run `git submodule update --init --recursive` in the repository folder.


To find out the cuda directory, it may be sufficient to run `which nvcc` which prints the location of nvcc.
```
which nvcc
/opt/cuda-11.1/bin/nvcc
```
In this example, /opt/cuda-11.1 is used with CARE.

**Comment by desmodus1984** [comment]
Hi,

I tried which nvcc and the directory does not contain the files expected for compiling the GPU-version.
I was looking at the different arguments; I have fastq files and I would like to know much is the benefit/running cost for using quality scores, and which other arguments would you recommend tunning for better correction?
My data is PE-100 reads. I have access to a high-performance cluster with 40/48 cores + 170GB mem.

Thanks;



Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by fkallen** [comment]
I recommend using quality scores if possible. This only has a small impact on runtime, but increases memory consumption. Reads of length 100 with quality scores should require around 128 MB per million reads.

You should enable the option `--candidateCorrection`, as well.

Regarding CUDA: Could you compile a .cu file with the following contents using the command `nvcc --dryrun file.cu` ?
`
int main(){
    return 0;
}
`

This will print the contents of relevant variables for nvcc such as include directories. You may be able to figure out the correct path required by CARE.
`
#$ INCLUDES="-I/opt/cuda-11.0/bin/../targets/x86_64-linux/include"  
#$ LIBRARIES=  "-L/opt/cuda-11.0/bin/../targets/x86_64-linux/lib/stubs" "-L/opt/cuda-11.0/bin/../targets/x86_64-linux/lib"
`

**Comment by desmodus1984** [comment]
Hi,

Thanks for all the help. I have two files with ~160M reads each but I believe that with the amount of GB should be fine.

I used the command as you suggested, and I got the following:
nvcc fatal   : Don't know what to do with '?'but I got the following output:
#$ INCLUDES="-I/apps/cuda/10.2.89/bin/../targets/x86_64-linux/include"  #$ LIBRARIES=  "-L/apps/cuda/10.2.89/bin/../targets/x86_64-linux/lib/stubs" "-L/apps/cuda/10.2.89/bin/../targets/x86_64-linux/lib"Then, I looked for the files nvcc and cub.h and I didn't find them in those directories. If you think it's important I will ask the staff of the HPC about the directories of cuda -if there is somewhere else to look for those files.
Also, the standard version of cuda is 10.2.89 but v 11.1 is already installed. Let me know if the current version is good for that.

Thanks again.



Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by fkallen** [comment]
Hi,

CUDA 10 good. With the provided output you may be able to use this path for CUDA: `/apps/cuda/10.2.89` . With a default installation the nvcc executable should be in `/apps/cuda/10.2.89/bin/nvcc`  . However, as you have probably noticed the nvcc which you used is part of CUDA 10.2, not CUDA 11. The CUB library has to be downloaded separately as it is not shipped together with CUDA 10.

**Comment by desmodus1984** [comment]
Hi,

Hope you are doing well. I wanted to mention you some results that I have found. I am doing variant calling of some samples with original reads/ error-corrected reads.
I used the following code to correct my reads:
./care-cpu -c 6 -i /fs/scratch/PHS0338/BGI-reads/IN33/IN33_2.fq.gz -d IN33 -o IN33_2.corr.fastq  --threads 48 --useQualityScores --memTotal 395G --candidateCorrection
I tested on a sample with ~10X coverage and the change in depth and coverage was minimal but, what actually shocked me is that in the non-error corrected reads the base quality was ~ 34.6 but in the error-corrected reads the baseq was 18.5.
Is there any reason why the base quality of the reads was significantly reduced? By the way, I using BGI-seq technology, and my sample was sequenced with the BGI-500 machine.

Best regards;



Juan Pablo Aguilar Cabezas

Ecology and Evolutionary Biology Ph.D. Candidate

Department of Biological Sciences

Ohio University, Athens OH

________________________________

**Comment by fkallen** [comment]
Hi
I'm not quite sure what you mean by change of base quality in your application. The quality scores of the corrected reads should be identical to those of uncorrected reads.

Note that CARE was only designed for Illumina reads with decent coverage of ~30+.

**Comment by desmodus1984** [comment]
Hi,

That's a detail that I didn't know of, didn't know that you needed a lot of coverage to use CARE.

I did test the effect of error-correction  ( reads PE 100bps) on mapping efficiency and the results were kinda shocked. Mapping quality got a little higher but the read quality did diminish, original average was ~34.6 and the CARE-corrected average 21.6.
Most importantly, the mean depth and median depths reduced too, as well as  the mean coverage. The biggest difference was in the number of mapped reads, of the original 750M, 44M didn't mapp after error-correction.
The effect on the low coverage samples was less abrupt.



Get BlueMail for Android<http://www.bluemail.me/r?b=16696>
On Jun 12, 2021, at 2:21 AM, fkallen ***@***.******@***.***>> wrote:

Hi
I'm not quite sure what you mean by change of base quality in your application. The quality scores of the corrected reads should be identical to those of uncorrected reads.

Note that CARE was only designed for Illumina reads with decent coverage of ~30+.
