### ISSUE TITLE
Expected X reads but file contains at least X+1 reads

### ISSUE THREAD

**Issue by rwhetten** [fkallen/CARE#4]
I compiled CARE for CPU use and that seems to have completed without issues. My read-correction job died after completing Step 0, which gave output
```
Running CARE CPU
STEP 0: Determine input size
Scanning file(s) to get number of reads and min/max sequence length.
----------------------------------------
File: AF.renamed.fastq
Reads: 4331801954
Minimum sequence length: 125
Maximum sequence length: 160
```
The error message after the job died was
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error! Expected 36834658 reads, but file contains at least 36834659 reads.
```
The command to start the job was  
```
care-cpu -d CARE -i AF.renamed.fastq -c 26.7 -t 35 -m 500G -o AF.cor.fastq
```
Would adjusting the batch size help with this problem?

**Comment by fkallen** [comment]
Hi, by default, CARE uses 32-bit numbers to enumerate reads. 4,331,801,954 cannot be represented with 32 bits.

You can enable 64-bit numbers in file `include/config.hpp` . In this line https://github.com/fkallen/CARE/blob/master/include/config.hpp#L11 change `uint32_t` to `uint64_t` and run `make clean` followed by `make`. Please let me know if other problems arise. I don't think I have ever tested such a large dataset.

Alternatively, you could remove some reads from your dataset such that there are only around 4,294,000,000 reads left and stick with 32-bit numbers.

**Comment by rwhetten** [comment]
OK, thanks - that was easy. This is actually only half of my data, which raises another question. The README says libraries are treated as unpaired, and if multiple files are provided, they are assumed to be from a single library. Given that pairing information is ignored, insert size is apparently not used, so it seems that the key issue in the assumption that they are from a single library is that all files represent sequences drawn from the same starting pool of genomic fragments - is this correct? I have multiple libraries made from the same DNA preparation of haploid tissue, but with different insert sizes. Can I combine all these libraries in a single run because they will all share the same set of genome sequences?

**Comment by fkallen** [comment]
Yes, that is correct. Insert size is not used currently. You should be able to use all files.

However, you may run into memory issues even with 500GB of ram. Your first file with 4.3B reads should require roughly 165 GB, without quality scores (which are disabled in your command). Adding to this will be the hash maps, which I expect to use around 200 GB for 8 maps with 4.3B reads (extrapolating from a test dataset with similar coverage). You could reduce memory usage of hash maps by editing the config file, setting `kmer_type` to `std::uint32_t` , which then requires the program parameter `-k 16`.
