### ISSUE TITLE
An error occurs when using "make cpu"

### ISSUE THREAD

**Issue by JappyPing** [fkallen/CARE#7]
Hi,
When I was compiling the source code "make cpu" , I got the following errors. Could you please give me some suggestions? Thanks so much.

mkdir build_correct_cpu
Compiling src/correct_cpu.cpp to build_correct_cpu/correct_cpu.o
Compiling src/correctionresultoutput.cpp to build_correct_cpu/correctionresultoutput.o
Compiling src/cpu_alignment.cpp to build_correct_cpu/cpu_alignment.o
Compiling src/cpuminhasherconstruction.cpp to build_correct_cpu/cpuminhasherconstruction.o
src/cpuminhasherconstruction.cpp:212:1: error: redefinition of 'const char _ZTSZN4care26AoSCpuSingleValueHashTableImSt4pairIjtEEC4EmfSt8functionIFmmEEEd_UlmE_ []'
  212 | }
      | ^
src/cpuminhasherconstruction.cpp:212:1: note: 'const char _ZTSZN4care26AoSCpuSingleValueHashTableImSt4pairIjtEEC4EmfSt8functionIFmmEEEd_UlmE_ [80]' previously defined here
make[1]: *** [build_correct_cpu/cpuminhasherconstruction.o] Error 1

Best regards,

Jappy

**Comment by fkallen** [comment]
Hi,
are you using GCC 11 by any chance ? This may be a known compiler bug but I will try to avoid it.

**Comment by JappyPing** [comment]
> 
Thanks for the quick reply.

Yes, I am using gcc 11.2.0. Which version should I use to avoid this issue? Thanks so much.

Best,
Jappy

**Comment by fkallen** [comment]
I am developing with GCC 9.4 which works fine for me. I may be able to push an update in a few hours.

**Comment by fkallen** [comment]
Could you checkout the latest commit and see if this resolved your issue? Tested it with GCC 11.1

**Comment by JappyPing** [comment]
> Could you checkout the latest commit and see if this resolved your issue? Tested it with GCC 11.1

Wa, amzing, thanks so much. It works well now.

Best,
Jappy
