### ISSUE TITLE
Questions on using care-cpu

### ISSUE THREAD

**Issue by JappyPing** [fkallen/CARE#8]
Hi,

Sorry to bother you again.
I have tried several time to correct different datasets using care-cpu, but every time, it seems that care-cpu stops at the following info.

example 1:
        ....
        STEP 2: Error correction
        correctionStatusFlagsPerRead bytes: 0.897481 MB
        Partial results may occupy 977.765 GB in memory. Remaining partial results will be stored in temp directory. 
        # elapsed time (STEP2): 7052.17s
        Correction throughput : ~133.445 reads/second.
        Constructed 29945 corrections. They occupy a total of 649429 bytes
        STEP 3: Constructing output file(s)
        sortValuesByGeneratedKeys: memoryLimitBytes = 1051181187072,numValues: 29945, sizeof(ValueType): 8, sizeof(IndexType): 4
        sortValuesByGeneratedKeysViaSortByKeyHost 
        requiredBytes: 479128, memoryLimitBytes: 1051181187072

example 2:
        ....
      Partial results may occupy 483.48 GB in memory. Remaining partial results will be stored in temp directory. 
      # elapsed time (STEP2): 16.0209s
      Correction throughput : ~58740.4 reads/second.
      Constructed 78058 corrections. They occupy a total of 2024737 bytes
      STEP 3: Constructing output file(s)
      sortValuesByGeneratedKeys: memoryLimitBytes = 520288481280,numValues: 78058, sizeof(ValueType): 8, sizeof(IndexType): 4
      sortValuesByGeneratedKeysViaSortByKeyHost 
      requiredBytes: 1248928, memoryLimitBytes: 520288481280
      # elapsed time (sort_results_by_read_id): 0.00289167s

Are the above info means that the memory is not enough? But my system shows very limit memory used, what's the  problem in this case? Could you please give me some suggestions? Thanks a lot.

Best,

Jappy

**Comment by fkallen** [comment]
This output is just for information. After sorting it should write the output file.
Could you share the settings you use ? Is the data set publicly available?

**Comment by JappyPing** [comment]
> This output is just for information. After sorting it should write the output file. Could you share the settings you use ? Is the data set publicly available?

Thanks for your help, I am correcting the publicly available dataset for testing, so the datasets should be no problem.

I used the command with the following settings.
`./care-cpu -c coverage -i input_file -o correct_file -t 60 -d output_dir --pairmode se`
As I calculated the coverage is quite big using the formula `read number * read length (262) / genome length`, so I set it as 128 directly. 

In the output directory, for each dataset, there are two output files like serializedobjectstorage-cppvst and serializedobjectstorage-CQ0fEa, but these files are empty. And please see the complete logs in [care.log](https://github.com/fkallen/CARE/files/9289093/care.log)

**Comment by fkallen** [comment]
`Estimated dataset coverage: 25683.6` 
This looks wrong. Can you confirm that you have actually set coverage to 128, not 25683.6?

serializedobjectstorage-****** are temporary files which may be empty if unused.

**Comment by JappyPing** [comment]
> `Estimated dataset coverage: 25683.6` This looks wrong. Can you confirm that you have actually set coverage to 128, not 25683.6?
> 
> serializedobjectstorage-****** are temporary files which may be empty if unused.

I ran many times and deleted most of the logs, only reserving the one record with the wrong coverage setting. But I reran the program using 128 (see the log [care2.log](https://github.com/fkallen/CARE/files/9290060/care2.log)), and after output information is complete, the process of care-cpu will be killed directly. Is it possible that the binary care-cpu [care-cpu.zip](https://github.com/fkallen/CARE/files/9290134/care-cpu.zip) I compiled is not right?

**Comment by fkallen** [comment]
Could you upload your input file (compressed)? I checked https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&page_size=10&acc=SRR1543970&display=metadata but this file has 1.2M reads, not 0.9M reads as in your file.

What is the reason for the program termination. Out of memory? Segmentation fault?

**Comment by fkallen** [comment]
For reference, a completed run should have output similar to the following:

```
STEP 3: Constructing output file(s)
sortValuesByGeneratedKeys: memoryLimitBytes = 25279528960,numValues: 302657, sizeof(ValueType): 8, sizeof(IndexType): 4
sortValuesByGeneratedKeysViaSortByKeyHost 
requiredBytes: 4842520, memoryLimitBytes: 25279528960
# elapsed time (sort_results_by_read_id): 0.00508752s
# elapsed time (merging): 17.8758s

# elapsed time (STEP3): 18.0293s
Construction of output file(s) finished.
```

**Comment by JappyPing** [comment]
> Could you upload your input file (compressed)? I checked https://trace.ncbi.nlm.nih.gov/Traces/index.html?view=run_browser&page_size=10&acc=SRR1543970&display=metadata but this file has 1.2M reads, not 0.9M reads as in your file.
> 
> What is the reason for the program termination. Out of memory? Segmentation fault?

No out-of-memory is raised, and the HPC cluster has enough memory to use. And there is no segmentation fault raised either. 

Thanks so much for checking the source data to help me. Actually, my task removed some reads from the source data; please find the modifications here [https://drive.google.com/file/d/1uBiGDAjmY6IJYHoyD1wNGh5Z7QYJNlWl/view?usp=sharing](url).

Are you using the binary care-cpu I shared above to correct the dataset SRR1543970?

**Comment by fkallen** [comment]
On my machine, no error occurs with your dataset. `./care-cpu -p -i new_tcr.seq.real_SRR1543970.fastq.gz -c 128 -o output.fastq -d . -m 27G -t 16 --pairmode SE -h 48`

I built the binary from source from this repository. I will not use your binary.

If you are using some job scheduling system on your cluster, maybe you can find out the reason why the job did not finish sucessfully.

**Comment by JappyPing** [comment]
> 



> On my machine, no error occurs with your dataset. `./care-cpu -p -i new_tcr.seq.real_SRR1543970.fastq.gz -c 128 -o output.fastq -d . -m 27G -t 16 --pairmode SE -h 48`
> 
> I built the binary from source from this repository. I will not use your binary.
> 
> If you are using some job scheduling system on your cluster, maybe you can find out the reason why the job did not finish sucessfully.

Thanks so much for your time and effort. I really appreciate it. 

Finally, I find the problem why I cannot get the result.  The error occurs for me because when I set the output filename, I also include its path. 

Thanks so much.

Best regards,

Jappy
