### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by ofleitas** [fkallen/CARE#9]
Hello 

I am trying run CARE but I get the follow error 

STEP 2: Error correction
correctionStatusFlagsPerRead bytes: 0.506677 MB
Partial results may occupy 0 GB in memory. Remaining partial results will be stored in temp directory. 
care-cpu: src/correct_cpu.cpp:204: care::SerializedObjectStorage care::cpu::correct_cpu(const care::ProgramOptions&, care::CpuMinhasher&, care::CpuReadStorage&): Assertion `batchReadIds.size() % 2 == 0' failed.
Aborted (core dumped)

Any suggestion ?
Best regards

**Comment by fkallen** [comment]
Hello,
please show the program arguments and the console output up to this point.

**Comment by ofleitas** [comment]
Hello
Follow the information 


(base) ofm@ofm-Aspire-E5-571G:~/src/CARE$ ./care-cpu -i /home/ofm/Documents/Genomics/Tutorial/Trimmed/SRR5137065_trimmed_1.fq -d /home/ofm/Documents/Genomics/Tutorial/Corrected_care -o SRR5137065_corrected_1.fastq -c 30 --pairmode PE
CARE CORRECT CPU will be started with the following parameters:
----------------------------------------
Output directory: /home/ofm/Documents/Genomics/Tutorial/Corrected_care
Estimated dataset coverage: 30
Input files: /home/ofm/Documents/Genomics/Tutorial/Trimmed/SRR5137065_trimmed_1.fq 
Output file names: SRR5137065_corrected_1.fastq 
Paired mode: PairedEnd
Number of hash tables / hash functions: 48
K-mer size for hashing: auto
Enforce number of hash tables: false
Threads: 1
Use quality scores: false
Bits per quality score: 8
Exclude ambigious reads: false
Alignment absolute required overlap: 30
Alignment relative required overlap: 0.3
Alignment max relative number of mismatches in overlap: 0.2
errorfactortuning: 0.06
coveragefactortuning: 0.6
Show progress bar: false
Output directory: /home/ofm/Documents/Genomics/Tutorial/Corrected_care
Temporary directory: /home/ofm/Documents/Genomics/Tutorial/Corrected_care
Save preprocessed reads to file: 
Load preprocessed reads from file: 
Save hash tables to file: 
Load hash tables from file: 
Maximum memory for hash tables: 2081009664
Maximum memory total: 3154751488
Hashtable load factor: 0.8
Fixed number of reads: 0
GZ compressed output: false
Correct candidate reads: false
Output correction quality labels: false
Max shift for candidate correction: 15
Correction type (anchor): 0 (Classic)
Correction type (cands): 0 (Classic)
ml-forestfile: 
ml-cands-forestfile: 
classification thresholds: 0.5 | 0.5
anchor sampling rate: 1
cands sampling rate: 0.01
pairedFilterThreshold: 0.06
maxForestTreesAnchor: 4294967295
maxForestTreesCands: 4294967295
ml-print-forestfile: anchorfeatures.txt
ml-cands-print-forestfile: candidatefeatures.txt
----------------------------------------
Running CARE CPU
STEP 1: Database construction
Converting paired reads of file /home/ofm/Documents/Genomics/Tutorial/Trimmed/SRR5137065_trimmed_1.fq
# elapsed time (init readstorage after construction): 0.0310319s
# elapsed time (build_readstorage): 1.00141s
Determined the following read properties:
----------------------------------------
Total number of reads: 531289
Minimum sequence length: 2
Maximum sequence length: 251
----------------------------------------
Will use k-mer length = 32 for hashing.
Reads with ambiguous bases: 0
reads memory usage: 0.0321622 GB on host
maxMemoryForTables = 2081009664 bytes
Constructing maps: 0(0) 1(1) 2(2) 3(3) 4(4) 5(5) 6(6) 7(7) 8(8) 9(9) 10(10) 11(11) 12(12) 13(13) 14(14) 15(15) 16(16) 17(17) 18(18) 19(19) 20(20) 21(21) 22(22) 23(23) 24(24) 25(25) 26(26) 27(27) 28(28) 29(29) 30(30) 31(31) 32(32) 33(33) 34(34) 35(35) 36(36) 37(37) 38(38) 39(39) 40(40) 41(41) 42(42) 43(43) 44(44) 45(45) 46(46) 47(47) 
Compacting
# elapsed time (build_minhasher): 9.76903s
Using minhasher type: Ordinary
CpuMinhasher can use 48 maps
hash tables memory usage: 0.127932 GB on host
# elapsed time (STEP1): 10.7705s
STEP 2: Error correction
correctionStatusFlagsPerRead bytes: 0.506677 MB
Partial results may occupy 0.777502 GB in memory. Remaining partial results will be stored in temp directory. 
care-cpu: src/correct_cpu.cpp:204: care::SerializedObjectStorage care::cpu::correct_cpu(const care::ProgramOptions&, care::CpuMinhasher&, care::CpuReadStorage&): Assertion `batchReadIds.size() % 2 == 0' failed.
Aborted (core dumped)
(base) ofm@ofm-Aspire-E5-571G:~/src/CARE$

**Comment by fkallen** [comment]
>--pairmode PE ,  Total number of reads: 531289

Your input file is not a proper paired-end file. That cannot work. With a single input file for paired-end correction, two consecutive reads are treated as a read pair. This is impossible with an odd number of reads.

**Comment by ofleitas** [comment]
Thank you very much for the help!!!
